### PR TITLE
Add patch to ignore 4.3 headers causing import issues

### LINKED ISSUE #7: from libtiff import  TIFF fails with libtiff 4.3.0 and pylibtiff 0.4.2
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
`from libitff import TIFF` failes with `libtiff 4.3.0` and `pylibtiff 0.4.2` 
```
('__attribute__((deprecated))', '#define TIFF_GCC_DEPRECATED __attribute__((deprecated))\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trygveas/miniconda3/envs/pytroll-3.8/lib/python3.8/site-packages/libtiff/__init__.py", line 20, in <module>
    from .libtiff_ctypes import libtiff, TIFF, TIFF3D
  File "/home/trygveas/miniconda3/envs/pytroll-3.8/lib/python3.8/site-packages/libtiff/libtiff_ctypes.py", line 113, in <module>
    value = eval(value)
  File "<string>", line 1, in <module>
NameError: name '__attribute__' is not defined
```
<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at /home/trygveas/miniconda3/envs/pytroll-3.8:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
affine                    2.3.0                      py_0    conda-forge
aggdraw                   1.3.12           py38h0bf2f78_1    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
bokeh                     2.3.3            py38h578d9bd_0    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
cftime                    1.5.0            py38hb5d20a5_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
curl                      7.78.0               hea6ffbf_0    conda-forge
cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
dask                      2021.7.2           pyhd8ed1ab_0    conda-forge
dask-core                 2021.7.2           pyhd8ed1ab_0    conda-forge
distributed               2021.7.2         py38h578d9bd_0    conda-forge
docutils                  0.17.1           py38h578d9bd_0    conda-forge
donfig                    0.6.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
fasteners                 0.16               pyhd8ed1ab_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
geos                      3.9.1                h9c3ff4c_2    conda-forge
geotiff                   1.6.0                h4f31c25_6    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
h5py                      3.3.0           nompi_py38h9915d05_100    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
kealib                    1.4.14               hcc255d8_2    conda-forge
krb5                      1.19.2               hcc1bbae_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0               10_openblas    conda-forge
libcblas                  3.9.0               10_openblas    conda-forge
libcurl                   7.78.0               h2574ce0_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.1.0               hc902ee8_8    conda-forge
libgdal                   3.3.1                h8f005ca_1    conda-forge
libgfortran-ng            11.1.0               h69a702a_8    conda-forge
libgfortran5              11.1.0               h6c583b3_8    conda-forge
libglib                   2.68.3               h3e27bee_0    conda-forge
libgomp                   11.1.0               hc902ee8_8    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0               10_openblas    conda-forge
libnetcdf                 4.8.0           nompi_hcd642e3_103    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.3                 hd57d9b9_0    conda-forge
librttopo                 1.1.0                h1185371_6    conda-forge
libspatialite             5.0.1                h8694cbe_5    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              11.1.0               h56837e0_8    conda-forge
libtiff                   0.4.2                    pypi_0    pypi
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzip                    1.8.0                h4de3113_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
netcdf4                   1.5.7           nompi_py38h5e9db54_100    conda-forge
numcodecs                 0.8.0            py38h709712a_0    conda-forge
numpy                     1.21.1           py38h9894fe3_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.1            py38h1abd341_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.3.1            py38h8e6f84c_0    conda-forge
pip                       21.2.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pooch                     1.4.0              pyhd8ed1ab_0    conda-forge
poppler                   21.03.0              h93df280_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.3                 h2510834_0    conda-forge
proj                      8.0.1                h277dcde_0    conda-forge
psutil                    5.8.0            py38h497a2fe_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycoast                   1.4.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pykdtree                  1.3.4            py38h0b5ebd8_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyorbital                 1.6.1              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.1.0            py38h4df08a6_3    conda-forge
pyresample                1.20.0           py38h1abd341_0    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pyspectral                0.10.5             pyhd8ed1ab_0    conda-forge
python                    3.8.10          h49503c6_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-geotiepoints       1.2.1            py38h5c078b8_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
rasterio                  1.2.6            py38h84fce68_2    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
satpy                     0.29.1.dev174+g19857250           dev_0    <develop>
scipy                     1.7.1            py38h56a6a73_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tiledb                    2.3.2                he87e0bf_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.62.0             pyhd8ed1ab_0    conda-forge
trollimage                1.15.1             pyhd8ed1ab_0    conda-forge
trollsift                 0.3.5              pyh44b312d_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzcode                    2021a                h7f98852_2    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h9d8b166_2    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zarr                      2.8.3              pyhd8ed1ab_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : pytroll-3.8
    active env location : /home/trygveas/miniconda3/envs/pytroll-3.8
            shell level : 1
       user config file : /home/trygveas/.condarc
 populated config files : /home/trygveas/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/trygveas/miniconda3  (writable)
      conda av data dir : /home/trygveas/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/trygveas/miniconda3/pkgs
                          /home/trygveas/.conda/pkgs
       envs directories : /home/trygveas/miniconda3/envs
                          /home/trygveas/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.0 CPython/3.9.1 Linux/5.4.0-77-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 41126:41126
             netrc file : None
           offline mode : False

```
</details>

To reproduce:
```
(pytroll-3.8) ubuntu@home:~/pytroll/satpy$ python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from libtiff import TIFF
('__attribute__((deprecated))', '#define TIFF_GCC_DEPRECATED __attribute__((deprecated))\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trygveas/miniconda3/envs/pytroll-3.8/lib/python3.8/site-packages/libtiff/__init__.py", line 20, in <module>
    from .libtiff_ctypes import libtiff, TIFF, TIFF3D
  File "/home/trygveas/miniconda3/envs/pytroll-3.8/lib/python3.8/site-packages/libtiff/libtiff_ctypes.py", line 113, in <module>
    value = eval(value)
  File "<string>", line 1, in <module>
NameError: name '__attribute__' is not defined
>>> 
```

If I downgrade `libtiff` to 4.2.0 like this :`conda install libtiff=4.2.0`

I get
```
(pytroll-3.8) ubuntu@home:~/pytroll/satpy$ python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from libtiff import TIFF
Generating '/home/trygveas/miniconda3/envs/pytroll-3.8/lib/python3.8/site-packages/libtiff/tiff_h_4_2_0.py' from '/home/trygveas/miniconda3/envs/pytroll-3.8/lib/../include/tiff.h'
>>> 
```
i.e. working.

So I'm not sure if this is a problem with `libtiff 4.3.0` or if some adjustments is needed for `pylibtiff 0.4.2`

### PR DESCRIPTION
**Pull request by djhoese**
Closes #7 

Without this, this is the current error being seen with libtiff 4.3.0. This patch is waiting to be merged in https://github.com/pearu/pylibtiff/pull/128.

```bash
$ conda create -n libtiff_test python=3.9 pylibtiff
$ conda activate libtiff_test
$ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libtiff
('__attribute__((deprecated))', '#define TIFF_GCC_DEPRECATED __attribute__((deprecated))\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidh/miniconda3/envs/libtiff_test/lib/python3.9/site-packages/libtiff/__init__.py", line 20, in <module>
    from .libtiff_ctypes import libtiff, TIFF, TIFF3D
  File "/home/davidh/miniconda3/envs/libtiff_test/lib/python3.9/site-packages/libtiff/libtiff_ctypes.py", line 113, in <module>
    value = eval(value)
  File "<string>", line 1, in <module>
NameError: name '__attribute__' is not defined
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by djhoese** [comment]
@conda-forge-admin please rerender

**Comment by djhoese** [comment]
FYI to the original author @robert-ancell

**Comment by djhoese** [comment]
Running this locally seems to work!

**Comment by djhoese** [comment]
@bgruening You seem to be the only other maintainer on this project. Would you mind reviewing this?

**Comment by dopplershift** [comment]
This patch seems reasonable enough to me, and if it goes bad somehow it won't be hard to undo. I'd say if you're happy @djhoese merge away!

**Comment by djhoese** [comment]
Thanks @dopplershift for the sanity check. Let's break stuff!

**Comment by djhoese** [comment]
Hm I just realized I probably should have re-rendered as this PR has been sitting here for a while. I'll see if the builds break and make a new PR if I have to.

**Pull request merged**
